1.3.1

In [ ]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1.3.1

In [17]:
z = np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1.3.2

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


1.3.3

In [ ]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.93105349 0.08219243 0.69410883]
  [0.38550455 0.46148429 0.07777492]
  [0.92804381 0.69465722 0.73574904]]

 [[0.10270592 0.67325711 0.38756656]
  [0.172332   0.63966076 0.73333772]
  [0.96090939 0.1058436  0.91405228]]

 [[0.07090087 0.24380496 0.35582335]
  [0.54924163 0.6435779  0.63503135]
  [0.25362754 0.07917992 0.3507325 ]]]


1.3.4

In [ ]:
# Задаем размер матрицы
n = 5
m = 5

# Создаем матрицу с нулями
matrix = [[0 for j in range(m)] for i in range(n)]

# Заполняем границы матрицы единицами
for i in range(n):
    for j in range(m):
        if i == 0 or j == 0 or i == n-1 or j == m-1:
            matrix[i][j] = 1

# Выводим матрицу
for i in range(n):
    for j in range(m):
        print(matrix[i][j], end=' ')
    print()


1 1 1 1 1 
1 0 0 0 1 
1 0 0 0 1 
1 0 0 0 1 
1 1 1 1 1 


1.3.6

In [ ]:
import numpy as np

# Создаем матрицу 3x4 со случайными значениями
matrix = np.random.rand(3, 4)

# Выводим матрицу
print(matrix)

# Выводим форму матрицы (количество строк и столбцов)
print("Форма матрицы:", matrix.shape)

# Выводим размер матрицы (общее количество элементов)
print("Размер матрицы:", matrix.size)

# Выводим размерность матрицы (количество осей)
print("Размерность матрицы:", matrix.ndim)


[[0.00757597 0.77784889 0.69417025 0.41291959]
 [0.55187169 0.73092136 0.86635453 0.24188592]
 [0.82360844 0.96156829 0.29236083 0.60848331]]
Форма матрицы: (3, 4)
Размер матрицы: 12
Размерность матрицы: 2


1.3.5

In [ ]:
import numpy as np

# Создаем массив случайных чисел
arr = np.random.randint(0, 10, 5)

# Выводим неотсортированный массив
print("Массив до сортировки:", arr)

# Сортируем массив по убыванию
arr_sorted = np.sort(arr)[::-1]
print("Массив после сортировки:", arr_sorted)


Массив до сортировки: [7 5 3 9 5]
Массив после сортировки: [9 7 5 5 3]


Библиотека pandas предоставляет две ключевые структуры данных:
Series и DataFrame.

Series – это одномерная структура данных, ее можно представить, как
таблицу с одной строкой. С Series можно работать как с обычным массивом
(обращаться по номеру индекса), и как с ассоциированным массивом, когда
можно использовать ключ для доступа к элементам данных.

DataFrame – это двумерная структура. Идейно она очень похожа на
обычную таблицу, что выражается в способе ее создания и работе с ее
элементами

2.3.1

In [ ]:
import pandas as pd
import numpy as np

# Создаем две Series (точки)
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

# Вычисляем квадраты разностей между соответствующими элементами a и b
squares = (a - b) ** 2

# Суммируем полученные квадраты
sum_of_squares = np.sum(squares)

# Извлекаем квадратный корень из полученной суммы
result = np.sqrt(sum_of_squares)
print("Евклидово расстояние между a и b:", result)


Евклидово расстояние между a и b: 5.196152422706632


2.3.2

In [13]:
import pandas as pd

# загрузить данные из файла
df = pd.read_csv('adult.csv')

# вывести первые 5 строк фрейма данных
print(df.head())


   age         workclass  education_num      marital_status  \
0   39         State-gov             13       Never-married   
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   
4   28           Private             13  Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
0       Adm-clerical  Not-in-family  White    Male            40.0   
1    Exec-managerial        Husband  White    Male            13.0   
2  Handlers-cleaners  Not-in-family  White    Male            40.0   
3  Handlers-cleaners        Husband  Other    Male            40.0   
4     Prof-specialty           Wife  Other  Female            40.0   

  native_country  capital income_status  
0  United-States   2174.0         <=50K  
1  United-States      0.0         <=50K  
2  United-States      0.0         <=50K  
3  United-States      0.0       

3.2.2

In [11]:
import pandas as pd

# Загружаем фрейм данных из CSV файла
df = pd.read_csv('iris.csv')
# Вычисляем минимальное и максимальное значение для первого признака
x_min = df["sepal_length_cm"].min()
x_max = df["sepal_length_cm"].max()

# Применяем минимаксное преобразование к первому признаку
df["sepal_length_cm_norm"] = (df["sepal_length_cm"] - x_min) / (x_max - x_min)

# Вычисляем среднее значение и стандартное отклонение для второго признака
mean = df["sepal_width_cm"].mean()
std = df["sepal_width_cm"].std()

# Применяем z-масштабирование ко второму признаку
df["sepal_width_cm_norm"] = (df["sepal_width_cm"] - mean) / std

# Выводим обновленный фрейм данных
print(df.head())

   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species  \
0              5.1             3.5              1.4             0.2  setosa   
1              4.9             3.0              1.4             0.2  setosa   
2              4.7             3.2              1.3             0.2  setosa   
3              4.6             3.1              1.5             0.2  setosa   
4              5.0             3.6              1.4             0.2  setosa   

   sepal_length_cm_norm  sepal_width_cm_norm  
0              0.222222             1.028611  
1              0.166667            -0.124540  
2              0.111111             0.336720  
3              0.083333             0.106090  
4              0.194444             1.259242  


2.3.3

In [20]:
import pandas as pd

# загрузить данные из файла
df = pd.read_csv('adult.csv')
print('2.2.5')
print(df.head(2))
print(df.tail(3))
print(df.shape)
print(df.describe())
print('2.2.6')
print((df.iloc[1::4]))
print('2.2.7')
df[df['hours_per_week'] > 40].head(5)

2.2.5
   age         workclass  education_num      marital_status       occupation  \
0   39         State-gov             13       Never-married     Adm-clerical   
1   50  Self-emp-not-inc             13  Married-civ-spouse  Exec-managerial   

    relationship   race gender  hours_per_week native_country  capital  \
0  Not-in-family  White   Male              40  United-States     2174   
1        Husband  White   Male              13  United-States        0   

  income_status  
0         <=50K  
1         <=50K  
       age     workclass  education_num      marital_status       occupation  \
45219   38       Private             13  Married-civ-spouse   Prof-specialty   
45220   44       Private             13            Divorced     Adm-clerical   
45221   35  Self-emp-inc             13  Married-civ-spouse  Exec-managerial   

      relationship   race gender  hours_per_week native_country  capital  \
45219      Husband  White   Male              50  United-States        0   
452

age         workclass  education_num      marital_status  \
7    52  Self-emp-not-inc              9  Married-civ-spouse   
8    31           Private             14       Never-married   
10   37           Private             10  Married-civ-spouse   
13   32           Private             12       Never-married   
14   34           Private              4  Married-civ-spouse   

          occupation   relationship   race  gender  hours_per_week  \
7    Exec-managerial        Husband  White    Male              45   
8     Prof-specialty  Not-in-family  White  Female              50   
10   Exec-managerial        Husband  Other    Male              80   
13             Sales  Not-in-family  Other    Male              50   
14  Transport-moving        Husband  Other    Male              45   

   native_country  capital income_status  
7   United-States        0          >50K  
8   United-States    14084          >50K  
10  United-States        0          >50K  
13  United-States        0         <=50K  
14          Other        0         <=50K

3.3.2

In [16]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
scaler1 = MinMaxScaler ()
scaler2 = StandardScaler ()
df = pd. read_csv(url)
df[['sepal_length_cm']] = scaler1.fit_transform(df[['sepal_length_cm']])
df [['sepal_width_cm']] = scaler2.fit_transform(df[['sepal_width_cm']])
df

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]